name: Ansible Playbook
author: Mauro Torrez
description: Run Ansible playbook

branding:
  icon: server
  color: gray-dark

inputs:
  playbook:
    description: Name of the playbook to execute.
    required: yes
  arguments:
    description: Extra arguments for the playbook.
    required: no
  working-directory:
    description: Working directory.
    required: no
  aws-access-key-id:
    description: AWS Access Key ID.
    required: no
  aws-secret-access-key:
    description: AWS Secret Access Key.
    required: no
  aws-session-token:
    description: AWS Session Token
    required: no
  aws-region:
    description: AWS Region, e.g. us-east-1
    required: no

outputs:
  command:
    description: Command to be executed.

runs:
  using: 'docker'
  image: 'Dockerfile'
